version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/football-auction
      - JWT_SECRET=your-super-secret-jwt-key-here
      - NEXTAUTH_URL=http://localhost:3000
      - WS_PORT=8080
    depends_on:
      - mongo
    networks:
      - football-auction-network

  websocket:
    build: .
    command: ["node", "scripts/websocket-server.js"]
    ports:
      - "8080:8080"
    environment:
      - WS_PORT=8080
    networks:
      - football-auction-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=football-auction
    networks:
      - football-auction-network

  # Optional: Redis for WebSocket scaling (if needed)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - football-auction-network

volumes:
  mongo-data:

networks:
  football-auction-network:
    driver: bridge
